### ISSUE TITLE
Leak due to not destroying the `autonumeric` element

### ISSUE THREAD

**Issue by rjbma** [mkg0/react-numeric#7]
Hi, 

I noticed there's a leak caused by not destroying the `autonumeric` element when this component is unmounted. 

The issue can be easily replicated in the example of this repo. We only need to switch between the **Code** and **Preview** tabs, and check that the **DOM nodes** counts in Chrome keeps increasing.
![image](https://user-images.githubusercontent.com/4331598/53577130-043b9b00-3b6d-11e9-9bad-be937dc1224d.png)

I can provide a pull request if you wish.

**Comment by dacopan** [comment]
@rjbma  please can you make a pull request

**Comment by rjbma** [comment]
@dacopan, seems the package owner already corrected the problem in commit 440770e3bb20b03c7e557a92e5ad4b045db1e1b4. 

I'm closing this issue.
